### ISSUE TITLE
whisper script unable to find ffmpeg

### ISSUE THREAD

**Issue by ayancey** [simon987/sist2-script-whisper#1]
```bash
 [INFO ]   Cloning https://github.com/simon987/sist2-python.git (to revision 2.0) to /tmp/pip-req-build-_whi_77q [INFO ]   Running command git clone --filter=blob:none --quiet https://github.com/simon987/sist2-python.git /tmp/pip-req-build-_whi_77q [INFO ]   Running command git checkout -q 09ae40fa08a17ada1ba68360a17a47af3ab83a72 [INFO ]   Resolved https://github.com/simon987/sist2-python.git to commit 09ae40fa08a17ada1ba68360a17a47af3ab83a72 [INFO ]   Preparing metadata (setup.py): started [INFO ]   Preparing metadata (setup.py): finished with status 'done' [INFO ] Collecting typer [INFO ]   Downloading typer-0.9.0-py3-none-any.whl (45 kB) [INFO ]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.9/45.9 KB 923.8 kB/s eta 0:00:00 [INFO ] Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from typer->-r requirements.txt (line 1)) (4.8.0) [INFO ] Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer->-r requirements.txt (line 1)) (8.1.7) [INFO ] Installing collected packages: typer [INFO ] Successfully installed typer-0.9.0 [INFO ] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv [INFO ] Executed setup script /sist2-admin/scripts/testwhisper/setup.sh, return code = 0 [ADMIN ] Initialized git repository in /sist2-admin/scripts/testwhisper [ADMIN ] Starting user script with executable='/sist2-admin/scripts/testwhisper/run.sh', index_path='/sist2-admin/scan-testingwhisper-2023-12-01 21:35:12.290273.sist2', extra_args='--model=base --num-threads=4 --color=#51da4c --tag' [ERROR ] Traceback (most recent call last):
 [ERROR ]   File "/sist2-admin/scripts/testwhisper/run.py", line 89, in <module>
 [ERROR ]     typer.run(main)
 [ERROR ]   File "/sist2-admin/scripts/testwhisper/run.py", line 63, in main
 [ERROR ]     text = whisper_stt(doc.path, num_threads, model)
 [ERROR ]   File "/sist2-admin/scripts/testwhisper/run.py", line 22, in whisper_stt
 [ERROR ]     subprocess.run([
 [ERROR ]   File "/usr/lib/python3.10/subprocess.py", line 503, in run
 [ERROR ]     with Popen(*popenargs, **kwargs) as process:
 [ERROR ]   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
 [ERROR ]     self._execute_child(args, executable, preexec_fn, close_fds,
 [ERROR ]   File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
 [ERROR ]     raise child_exception_type(errno_num, err_msg, err_filename)
 [ERROR ] FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
```

**Comment by ayancey** [comment]
Running sist2-admin and elasticsearch using the docker-compose example in the sist2 README. Fixed this issue by getting a shell into the sis2-admin container and apt installing ffmpeg.
